# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2779e984fb3bf45c8a9c99cc0add90d00fdbeef7bc374854fb1bb290b2bc48029e8e974de90154e338f810df963dfaac1f752353c76c200339c617d2c751f31e

test:
  secret_key_base: 51de69db50d6fb75a5a48667b89a05142c0fd9546cf6c860afb5128a6ee3053a64940a188d8e2847c2aa01cc423c4648534a44413098495c41c916dab261b680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
